import type { TopicTexts } from "./topicStructure";

export const englishTopicTexts: TopicTexts = {
  groups: {
    fundamentals: "App Router fundamentals",
    rendering: "Rendering strategies",
    components: "Server and Client Components",
    data: "Data fetching and caching",
    "server-actions": "Server Actions and forms",
    "advanced-routing": "Advanced routing",
    errors: "Error handling",
    metadata: "Metadata and SEO",
    optimization: "Optimization and performance",
    testing: "Testing",
  },
  topics: {
    "/fundamentals/file-conventions": { title: "File conventions", summary: "page, layout, template, loading, error, not-found, route groups, and private folders." },
    "/fundamentals/dynamic-segments": { title: "Dynamic segments", summary: "[slug], catch-all [...slug], and optional catch-all [[...slug]]." },
    "/fundamentals/parallel-routes": { title: "Parallel routes", summary: "Rendering several pages in one layout with @slot folders." },
    "/fundamentals/intercepting-routes": { title: "Intercepting routes", summary: "Showing another route in the current context with (.)folder." },
    "/fundamentals/navigation": { title: "Navigation", summary: "Link, useRouter, usePathname, useSearchParams, and prefetching." },
    "/rendering/static-vs-dynamic": { title: "Static vs dynamic rendering", summary: "When Next.js prerenders a route and when it renders per request." },
    "/rendering/isr": { title: "Incremental Static Regeneration", summary: "Time-based and on-demand revalidation of prerendered output." },
    "/rendering/streaming": { title: "Streaming", summary: "loading.tsx and Suspense boundaries in the Server Component tree." },
    "/rendering/ppr": { title: "Partial Prerendering", summary: "\"use cache\", cacheLife, and cacheTag with a static shell." },
    "/components/use-client-boundary": { title: "The use client boundary", summary: "What can and cannot cross the boundary as props." },
    "/components/composition": { title: "Composition", summary: "Passing Client Components as children to Server Components." },
    "/components/pitfalls": { title: "Pitfalls", summary: "Server Component defaults and the mistakes they invite." },
    "/data/fetch-extensions": { title: "fetch() extensions", summary: "cache, next.revalidate, and next.tags." },
    "/data/cache-layers": { title: "Cache layers", summary: "Data Cache, Full Route Cache, Router Cache, and Request Memoization." },
    "/data/parallel-vs-sequential": { title: "Parallel vs sequential fetching", summary: "The waterfall problem and how to avoid it." },
    "/data/revalidation": { title: "Revalidation", summary: "revalidatePath and revalidateTag." },
    "/data/use-cache-migration": { title: "Migrating to use cache", summary: "Moving from unstable_cache to \"use cache\"." },
    "/server-actions/basics": { title: "Server Actions basics", summary: "\"use server\" and calling actions from Client and Server Components." },
    "/server-actions/forms": { title: "Forms", summary: "form action and progressive enhancement." },
    "/server-actions/form-hooks": { title: "Form hooks", summary: "useActionState, useFormStatus, and useOptimistic." },
    "/server-actions/validation-and-redirect": { title: "Validation and redirect", summary: "Validating input, reporting errors, and redirecting after an action." },
    "/advanced-routing/route-handlers": { title: "Route Handlers", summary: "HTTP methods with NextRequest and NextResponse." },
    "/advanced-routing/proxy": { title: "Proxy", summary: "Rewrites, redirects, and personalization in proxy.ts." },
    "/advanced-routing/runtimes": { title: "Runtimes", summary: "Edge Runtime vs Node.js runtime." },
    "/errors/error-boundaries": { title: "Error boundaries", summary: "error.tsx vs global-error.tsx." },
    "/errors/not-found": { title: "Not found", summary: "not-found.tsx and notFound()." },
    "/errors/actions-and-handlers": { title: "Actions and handlers", summary: "Error handling in Server Actions and Route Handlers." },
    "/metadata/generate-metadata": { title: "generateMetadata", summary: "Static and dynamic metadata, and metadataBase." },
    "/metadata/sitemap-robots": { title: "Sitemap and robots", summary: "sitemap.ts and robots.ts." },
    "/metadata/og-images": { title: "Open Graph images", summary: "Generated images with opengraph-image.tsx." },
    "/optimization/image": { title: "next/image", summary: "Lazy loading, srcset, priority, and LCP." },
    "/optimization/font": { title: "next/font", summary: "Self-hosting fonts and avoiding layout shift." },
    "/optimization/dynamic-import": { title: "next/dynamic", summary: "Code splitting and ssr: false." },
    "/optimization/bundlers": { title: "Turbopack vs Webpack", summary: "The mental model and when to use each." },
    "/optimization/web-vitals": { title: "Web Vitals", summary: "Bundle analysis and Core Web Vitals." },
    "/testing/server-vs-client": { title: "Server vs Client Components", summary: "Testing each kind of component." },
    "/testing/mocking-and-actions": { title: "Mocking and Server Actions", summary: "Mocking fetch and cache, and testing Server Actions." },
  },
};
