import type { TopicTexts } from "./topicStructure";

export const polishTopicTexts: TopicTexts = {
  groups: {
    fundamentals: "Podstawy App Routera",
    rendering: "Strategie renderowania",
    components: "Komponenty serwerowe i klienckie",
    data: "Pobieranie danych i cache",
    "server-actions": "Server Actions i formularze",
    "advanced-routing": "Zaawansowany routing",
    errors: "Obsługa błędów",
    metadata: "Metadane i SEO",
    optimization: "Optymalizacja i wydajność",
    testing: "Testowanie",
  },
  topics: {
    "/fundamentals/file-conventions": { title: "Konwencje plików", summary: "page, layout, template, loading, error, not-found, grupy tras i foldery prywatne." },
    "/fundamentals/dynamic-segments": { title: "Segmenty dynamiczne", summary: "[slug], catch-all [...slug] i opcjonalny catch-all [[...slug]]." },
    "/fundamentals/parallel-routes": { title: "Trasy równoległe", summary: "Renderowanie kilku stron w jednym layoucie za pomocą folderów @slot." },
    "/fundamentals/intercepting-routes": { title: "Trasy przechwytujące", summary: "Pokazanie innej trasy w bieżącym kontekście za pomocą (.)folder." },
    "/fundamentals/navigation": { title: "Nawigacja", summary: "Link, useRouter, usePathname, useSearchParams i prefetching." },
    "/rendering/static-vs-dynamic": { title: "Renderowanie statyczne i dynamiczne", summary: "Kiedy Next.js prerenderuje trasę, a kiedy renderuje ją przy każdym żądaniu." },
    "/rendering/isr": { title: "Incremental Static Regeneration", summary: "Rewalidacja prerenderowanego wyniku w czasie i na żądanie." },
    "/rendering/streaming": { title: "Streaming", summary: "loading.tsx i granice Suspense w drzewie komponentów serwerowych." },
    "/rendering/ppr": { title: "Partial Prerendering", summary: "\"use cache\", cacheLife i cacheTag ze statyczną powłoką." },
    "/components/use-client-boundary": { title: "Granica use client", summary: "Co może, a co nie może przekroczyć granicy jako propsy." },
    "/components/composition": { title: "Kompozycja", summary: "Przekazywanie komponentów klienckich jako children do komponentów serwerowych." },
    "/components/pitfalls": { title: "Pułapki", summary: "Domyślne zachowanie komponentów serwerowych i błędy, które sprowokuje." },
    "/data/fetch-extensions": { title: "Rozszerzenia fetch()", summary: "cache, next.revalidate i next.tags." },
    "/data/cache-layers": { title: "Warstwy cache", summary: "Data Cache, Full Route Cache, Router Cache i Request Memoization." },
    "/data/parallel-vs-sequential": { title: "Pobieranie równoległe i sekwencyjne", summary: "Problem wodospadu (waterfall) i jak go uniknąć." },
    "/data/revalidation": { title: "Rewalidacja", summary: "revalidatePath i revalidateTag." },
    "/data/use-cache-migration": { title: "Migracja do use cache", summary: "Przejście z unstable_cache na \"use cache\"." },
    "/server-actions/basics": { title: "Podstawy Server Actions", summary: "\"use server\" i wywoływanie akcji z komponentów klienckich i serwerowych." },
    "/server-actions/forms": { title: "Formularze", summary: "form action i progresywne ulepszanie." },
    "/server-actions/form-hooks": { title: "Hooki formularzy", summary: "useActionState, useFormStatus i useOptimistic." },
    "/server-actions/validation-and-redirect": { title: "Walidacja i przekierowanie", summary: "Walidacja danych, raportowanie błędów i przekierowanie po akcji." },
    "/advanced-routing/route-handlers": { title: "Route Handlers", summary: "Metody HTTP z NextRequest i NextResponse." },
    "/advanced-routing/proxy": { title: "Proxy", summary: "Rewrites, redirecty i personalizacja w proxy.ts." },
    "/advanced-routing/runtimes": { title: "Środowiska uruchomieniowe", summary: "Edge Runtime a środowisko Node.js." },
    "/errors/error-boundaries": { title: "Granice błędów", summary: "error.tsx a global-error.tsx." },
    "/errors/not-found": { title: "Nie znaleziono", summary: "not-found.tsx i notFound()." },
    "/errors/actions-and-handlers": { title: "Akcje i handlery", summary: "Obsługa błędów w Server Actions i Route Handlers." },
    "/metadata/generate-metadata": { title: "generateMetadata", summary: "Metadane statyczne i dynamiczne oraz metadataBase." },
    "/metadata/sitemap-robots": { title: "Sitemap i robots", summary: "sitemap.ts i robots.ts." },
    "/metadata/og-images": { title: "Obrazy Open Graph", summary: "Generowane obrazy z opengraph-image.tsx." },
    "/optimization/image": { title: "next/image", summary: "Lazy loading, srcset, priority i LCP." },
    "/optimization/font": { title: "next/font", summary: "Self-hosting fontów i unikanie przesunięć layoutu." },
    "/optimization/dynamic-import": { title: "next/dynamic", summary: "Podział kodu i ssr: false." },
    "/optimization/bundlers": { title: "Turbopack a Webpack", summary: "Model mentalny i kiedy użyć którego." },
    "/optimization/web-vitals": { title: "Web Vitals", summary: "Analiza bundla i Core Web Vitals." },
    "/testing/server-vs-client": { title: "Komponenty serwerowe i klienckie", summary: "Testowanie każdego rodzaju komponentu." },
    "/testing/mocking-and-actions": { title: "Mockowanie i Server Actions", summary: "Mockowanie fetch i cache oraz testowanie Server Actions." },
  },
};
